[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.1"  # 👈 Use a real, stable Node version (or 18.x)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
